version: '3'
services:


  mongo:
    container_name: mongodb
    
    image: mongo

    volumes:
      - './data/mongo:/data/db'
    ports:
      - '27017:27017'
  
  web:
    container_name: nginx
    image: 'nginx:stable-alpine'
    volumes:
      - './nginx/backend.conf:/etc/nginx/conf.d/default.conf'
      - './nginx/proxy_reverse.conf:/etc/nginx/proxy_reverse.conf'
    ports:
      - '80:80'
    environment:
      - NGINX_PORT=80
    command:
      - nginx-debug
      - '-g'
      - daemon off;
    links:
      - nodejs

    
  nodejs:
    container_name: backend
    restart: always
    build:
      context: ./backend
    volumes:
      - './backend:/app'
    environment:
      - HOST=localhost
    
    ports:
      - '3000:3000'
    links:
      - mongo
 
  
  
